using UnityEngine;
using System.Collections.Generic;
using System.Text;

[CreateAssetMenu(fileName = "New Stat Upgrade Card", menuName = "Cards/Stat Upgrade Card")]
public class StatUpgradeCard : Card
{

    [SerializeField] private bool autoGenerateDescription = true;
    public List<StatType> statTypes = new List<StatType>();
    public List<float> statValues = new List<float>();


    public override void OnValidate()
    {
        base.OnValidate();

        if (autoGenerateDescription)
        {
            GenerateDescription();
        }
    }

    private void GenerateDescription()
    {
        StringBuilder sb = new StringBuilder();

        for (int i = 0; i < statTypes.Count; i++)
        {
            if (statValues[i] > 0)
            {
                sb.Append("Increases ");
            }
            else
            {
                sb.Append("Decreases ");
            }

            sb.Append(statTypes[i].ToString());
            sb.Append(" by ");
            sb.Append(statValues[i].ToString("+#0.##;-#0.##;0"));
            sb.Append(". ");
        }

        description = sb.ToString();
    }

    public override void OnEnable()
    {
        base.OnEnable();
        cardType = CardType.StatUpgrade;
    }
}